/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author pjroj
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public RegistrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        habitacionDisponible = new javax.swing.JButton();
        JLabel8 = new javax.swing.JLabel();
        Jlabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        Jlabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        JLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        salida = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        llegada = new javax.swing.JTextField();
        JLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        menu2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        JLabel10 = new javax.swing.JLabel();
        guardarcliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        menu.setBackground(new java.awt.Color(0, 51, 102));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar Cliente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        habitacionDisponible.setBackground(new java.awt.Color(51, 102, 255));
        habitacionDisponible.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        habitacionDisponible.setText("Buscar habitaciones");
        habitacionDisponible.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        habitacionDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionDisponibleActionPerformed(evt);
            }
        });
        jPanel2.add(habitacionDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 170, 30));

        JLabel8.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel8.setForeground(new java.awt.Color(51, 51, 51));
        JLabel8.setText("Fecha de salida:");
        jPanel2.add(JLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 20));

        Jlabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Jlabel1.setForeground(new java.awt.Color(51, 51, 51));
        Jlabel1.setText("Cédula:");
        jPanel2.add(Jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        JLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(51, 51, 51));
        JLabel2.setText("Primer nombre:");
        jPanel2.add(JLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        JLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(51, 51, 51));
        JLabel3.setText("Segundo nombre:");
        jPanel2.add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        Jlabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Jlabel4.setForeground(new java.awt.Color(51, 51, 51));
        Jlabel4.setText("Email:");
        jPanel2.add(Jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        JLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel5.setForeground(new java.awt.Color(51, 51, 51));
        JLabel5.setText("Número de habitación disponible:");
        jPanel2.add(JLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, 20));

        JLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel6.setForeground(new java.awt.Color(51, 51, 51));
        JLabel6.setText("Teléfono celular:");
        jPanel2.add(JLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 20));

        JLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel7.setForeground(new java.awt.Color(51, 51, 51));
        JLabel7.setText("Fecha de llegada:");
        jPanel2.add(JLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, 20));

        email.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, -1));

        genero.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, -1));

        salida.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 210, -1));

        apellido.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, -1));

        ci.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, -1));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        telefono.setBackground(new java.awt.Color(255, 255, 255));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        jPanel2.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, -1));

        llegada.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, -1));

        JLabel9.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel9.setForeground(new java.awt.Color(51, 51, 51));
        JLabel9.setText("Género: Male/Female");
        jPanel2.add(JLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 20));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, -1));

        menu2.setBackground(new java.awt.Color(51, 102, 255));
        menu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu2.setText("Ir al menú");
        menu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        jPanel2.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 150, 30));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 160, -1));

        JLabel10.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel10.setForeground(new java.awt.Color(51, 51, 51));
        JLabel10.setText("Tipo de Habitación:");
        jPanel2.add(JLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        guardarcliente.setBackground(new java.awt.Color(51, 102, 255));
        guardarcliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        guardarcliente.setText("Guardar Cliente");
        guardarcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(guardarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 990, 410));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 410));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habitacionDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionDisponibleActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel10;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel JLabel8;
    private javax.swing.JLabel JLabel9;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JLabel Jlabel4;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField email;
    private javax.swing.JTextField genero;
    private javax.swing.JButton guardarcliente;
    private javax.swing.JButton habitacionDisponible;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField llegada;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField salida;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
