package Interfaces;

/**
 *
 * @author nicolasplanas
 */
public class W extends javax.swing.JFrame {

    /**
     * Creates new form W
     */
    public W() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reservations_bttn = new javax.swing.JButton();
        rooms_bttn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search_client_bttn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(804, 527));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Powerr", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOTEL BUDAPEST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 620, 150));

        reservations_bttn.setFont(new java.awt.Font("Beirut", 1, 18)); // NOI18N
        reservations_bttn.setText("RESERVACIONES");
        reservations_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservations_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(reservations_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 220, 40));

        rooms_bttn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        rooms_bttn.setText("HABITACIONES");
        rooms_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rooms_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(rooms_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 190, 40));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        search_client_bttn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        search_client_bttn.setText("BUSCAR CLIENTE");
        search_client_bttn.setActionCommand("BUSCAR CLIENTE");
        search_client_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_client_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(search_client_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, 40));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("CHECK-OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 190, 40));

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setText("CHECK-IN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservations_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservations_bttnActionPerformed
        this.setVisible(false);
        W2 w2 = new W2();
        w2.setVisible(true);
    }//GEN-LAST:event_reservations_bttnActionPerformed

    private void rooms_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rooms_bttnActionPerformed
        this.setVisible(false);
        W3 w3 = new W3();
        w3.setVisible(true);
    }//GEN-LAST:event_rooms_bttnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void search_client_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_client_bttnActionPerformed
        this.setVisible(false);
        W1 w1 = new W1();
        w1.setVisible(true);
    }//GEN-LAST:event_search_client_bttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        W5 w5 = new W5();
        w5.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        W4 w4 = new W4();
        w4.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new W().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reservations_bttn;
    private javax.swing.JButton rooms_bttn;
    private javax.swing.JButton search_client_bttn;
    // End of variables declaration//GEN-END:variables
}
