/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Class_Client;
import Main.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author pjroj
 */
public class Check_Out extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Check_Out() {
        setTitle("CheckOut");
        setSize(350,360);
        setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menu2 = new javax.swing.JButton();
        hacerCheckOut = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        JLabel4 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        JLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        menu.setBackground(new java.awt.Color(0, 51, 102));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check-out");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu2.setBackground(new java.awt.Color(51, 102, 255));
        menu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu2.setText("Ir al menú");
        menu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        jPanel2.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 30));

        hacerCheckOut.setBackground(new java.awt.Color(51, 102, 255));
        hacerCheckOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hacerCheckOut.setText("Realizar Check-Out");
        hacerCheckOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hacerCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerCheckOutActionPerformed(evt);
            }
        });
        jPanel2.add(hacerCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 150, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, -1));

        JLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(51, 51, 51));
        JLabel4.setText("Primer nombre:");
        jPanel2.add(JLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, -1));

        JLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(51, 51, 51));
        JLabel3.setText("Segundo nombre:");
        jPanel2.add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 360));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 360));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hacerCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerCheckOutActionPerformed
        try {
            String nam = name.getText().substring(0, 1).toUpperCase() + name.getText().substring(1).toLowerCase();
            String lastnam = lastname.getText().substring(0, 1).toUpperCase() + lastname.getText().substring(1).toLowerCase();
            Class_Client searchResult = Global.getClients().checkOutClient(nam,lastnam);
            
            if (searchResult.getName().equals(nam) && (searchResult.getLastname().equals(lastnam))) {
                JOptionPane.showMessageDialog(null,"El cliente " + searchResult.getName() + " " + searchResult.getLastname() + " fue añadido al historial de habitación y eliminado de los hospedados con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado!");
            }
            name.setText("");
            lastname.setText("");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cliente no encontrado!");
        }
    }//GEN-LAST:event_hacerCheckOutActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_Out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton hacerCheckOut;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu2;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
