/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Class_Client;
import Main.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author pjroj
 */
public class Check_Out extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Check_Out() {
        initComponents();
        setTitle("CheckOut");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        JLabel4 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        check_in_btn = new javax.swing.JButton();
        back_to_menu_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(0, 51, 102));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 378));
        setPreferredSize(new java.awt.Dimension(600, 37));
        setSize(new java.awt.Dimension(600, 378));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        jLabel4.setFont(new java.awt.Font("Kubo Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 25, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CHECK-OUT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 560, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 210, -1));

        JLabel4.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(75, 25, 0));
        JLabel4.setText("Primer nombre:");
        getContentPane().add(JLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        JLabel3.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(75, 25, 0));
        JLabel3.setText("Segundo nombre:");
        getContentPane().add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, -1));

        check_in_btn.setBackground(new java.awt.Color(75, 25, 0));
        check_in_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        check_in_btn.setForeground(new java.awt.Color(255, 248, 231));
        check_in_btn.setText("Aceptar");
        check_in_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        check_in_btn.setOpaque(true);
        check_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_btnActionPerformed(evt);
            }
        });
        getContentPane().add(check_in_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, 30));

        back_to_menu_btn.setBackground(new java.awt.Color(75, 25, 0));
        back_to_menu_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        back_to_menu_btn.setForeground(new java.awt.Color(255, 248, 231));
        back_to_menu_btn.setText("Volver al menú");
        back_to_menu_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_to_menu_btn.setOpaque(true);
        back_to_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_menu_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_to_menu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Window_Check_Out.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_btnActionPerformed
        try {
            String nam = name.getText().substring(0, 1).toUpperCase() + name.getText().substring(1).toLowerCase();
            String lastnam = lastname.getText().substring(0, 1).toUpperCase() + lastname.getText().substring(1).toLowerCase();
            Class_Client searchResult = Global.getClients().checkOutClient(nam,lastnam);

            if (searchResult.getName().equals(nam) && (searchResult.getLastname().equals(lastnam))) {
                int room_number = Integer.parseInt(searchResult.getRoomNumber());
                Global.getRooms().setAvailable(room_number);
                JOptionPane.showMessageDialog(null, "El cliente " + searchResult.getName() + " " + searchResult.getLastname() + " fue añadido al historial de habitación y eliminado de los hospedados con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado!");
            }
            name.setText("");
            lastname.setText("");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cliente no encontrado!");
        }
    }//GEN-LAST:event_check_in_btnActionPerformed

    private void back_to_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_menu_btnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_to_menu_btnActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_Out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton back_to_menu_btn;
    private javax.swing.JButton check_in_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton menu;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
