/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Class_Client;
import Classes.Class_Reservation;
import Main.Global;
import Nodes.Node_Room;
import javax.swing.JOptionPane;

/**
 *
 * @author pjroj
 */
public class Check_In extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Check_In() {
        initComponents();
        setTitle("CheckIn");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ci = new javax.swing.JTextField();
        Jlabel2 = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        Jlabel5 = new javax.swing.JLabel();
        roomNumber = new javax.swing.JLabel();
        Jlabel4 = new javax.swing.JLabel();
        floorNumber = new javax.swing.JLabel();
        check_in_btn = new javax.swing.JButton();
        back_to_menu_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(0, 51, 102));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, -1));

        Jlabel2.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        Jlabel2.setForeground(new java.awt.Color(75, 25, 0));
        Jlabel2.setText("Cédula:");
        getContentPane().add(Jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        Jlabel3.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        Jlabel3.setForeground(new java.awt.Color(75, 25, 0));
        Jlabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel3.setText("Habitación asignada:");
        getContentPane().add(Jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 20));

        Jlabel5.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        Jlabel5.setForeground(new java.awt.Color(75, 25, 0));
        Jlabel5.setText("Número:");
        getContentPane().add(Jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 20));

        roomNumber.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        roomNumber.setForeground(new java.awt.Color(75, 25, 0));
        roomNumber.setText("...");
        getContentPane().add(roomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 90, 20));

        Jlabel4.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        Jlabel4.setForeground(new java.awt.Color(75, 25, 0));
        Jlabel4.setText("Piso:");
        getContentPane().add(Jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        floorNumber.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        floorNumber.setForeground(new java.awt.Color(75, 25, 0));
        floorNumber.setText("...");
        getContentPane().add(floorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, 20));

        check_in_btn.setBackground(new java.awt.Color(75, 25, 0));
        check_in_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        check_in_btn.setForeground(new java.awt.Color(255, 248, 231));
        check_in_btn.setText("Aceptar");
        check_in_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        check_in_btn.setOpaque(true);
        check_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_btnActionPerformed(evt);
            }
        });
        getContentPane().add(check_in_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        back_to_menu_btn.setBackground(new java.awt.Color(75, 25, 0));
        back_to_menu_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        back_to_menu_btn.setForeground(new java.awt.Color(255, 248, 231));
        back_to_menu_btn.setText("Volver al menú");
        back_to_menu_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_to_menu_btn.setOpaque(true);
        back_to_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_menu_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_to_menu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 30));

        jLabel5.setFont(new java.awt.Font("Kubo Sans", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 25, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CHECK-IN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Window_Check_In.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_btnActionPerformed
        try {
            // BUSCAMOS AL CLIENTE.
            int id = Integer.parseInt(ci.getText());
            Class_Client searchResult = Global.getClients().checkInClient(id);
            
            //resultCheckIn.setText(Global.getClients().searchClient(searchResult.getName(), searchResult.getLastname()));
            Class_Reservation search_result = Global.getClients().searchClient(searchResult.getName(),searchResult.getLastname());
            roomNumber.setText(search_result.getClient().getRoomNumber());
            Node_Room room = Global.getRooms().search(Integer.parseInt(search_result.getClient().getRoomNumber()), Global.getRooms().getRoot());
            floorNumber.setText(Integer.toString(room.getRoom().getFloor()));
            ci.setText("");            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor introduzca un valor numérico");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error! Algo ha salido mal!");
        }
    }//GEN-LAST:event_check_in_btnActionPerformed

    private void back_to_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_menu_btnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_to_menu_btnActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel2;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Jlabel4;
    private javax.swing.JLabel Jlabel5;
    private javax.swing.JButton back_to_menu_btn;
    private javax.swing.JButton check_in_btn;
    private javax.swing.JTextField ci;
    private javax.swing.JLabel floorNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton menu;
    private javax.swing.JLabel roomNumber;
    // End of variables declaration//GEN-END:variables
}
