/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Main.Global;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pjroj
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Inicio() {
        setTitle("Inicio");
        setSize(880, 370);
        setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarReservaciones = new javax.swing.JPanel();
        nombreArcEstado = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        cargaEstado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cargarReservac = new javax.swing.JButton();
        cargarHabitaciones = new javax.swing.JButton();
        cargaHistorico = new javax.swing.JButton();
        nombreArcRes = new javax.swing.JLabel();
        nombreArcHabit = new javax.swing.JLabel();
        nombreArcHistor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        cargarReservaciones.setBackground(new java.awt.Color(153, 204, 255));
        cargarReservaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreArcEstado.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        nombreArcEstado.setForeground(new java.awt.Color(255, 255, 255));
        nombreArcEstado.setText("...");
        cargarReservaciones.add(nombreArcEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 310, 20));

        menu.setBackground(new java.awt.Color(51, 102, 255));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        cargarReservaciones.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 150, 30));

        cargaEstado.setBackground(new java.awt.Color(51, 102, 255));
        cargaEstado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cargaEstado.setText("Archivo de Estado");
        cargaEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaEstadoActionPerformed(evt);
            }
        });
        cargarReservaciones.add(cargaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 30));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Archivo seleccionado:");
        cargarReservaciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reception");
        cargarReservaciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cargarReservac.setBackground(new java.awt.Color(51, 102, 255));
        cargarReservac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cargarReservac.setText("Archivo de Reservaciones");
        cargarReservac.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargarReservac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarReservacActionPerformed(evt);
            }
        });
        cargarReservaciones.add(cargarReservac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        cargarHabitaciones.setBackground(new java.awt.Color(51, 102, 255));
        cargarHabitaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cargarHabitaciones.setText("Archivo de Habitaciones");
        cargarHabitaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarHabitacionesActionPerformed(evt);
            }
        });
        cargarReservaciones.add(cargarHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 30));

        cargaHistorico.setBackground(new java.awt.Color(51, 102, 255));
        cargaHistorico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cargaHistorico.setText("Archivo de Historico");
        cargaHistorico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargaHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaHistoricoActionPerformed(evt);
            }
        });
        cargarReservaciones.add(cargaHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 30));

        nombreArcRes.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        nombreArcRes.setForeground(new java.awt.Color(255, 255, 255));
        nombreArcRes.setText("...");
        cargarReservaciones.add(nombreArcRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 310, 20));

        nombreArcHabit.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        nombreArcHabit.setForeground(new java.awt.Color(255, 255, 255));
        nombreArcHabit.setText("...");
        cargarReservaciones.add(nombreArcHabit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 310, 20));

        nombreArcHistor.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        nombreArcHistor.setForeground(new java.awt.Color(255, 255, 255));
        nombreArcHistor.setText("...");
        cargarReservaciones.add(nombreArcHistor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 310, 20));

        getContentPane().add(cargarReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 540, 370));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/campanaimagen.png"))); // NOI18N
        imagen.setPreferredSize(new java.awt.Dimension(106, 102));
        jPanel4.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 290));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 190));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean FileIsEmpty(){
        return Global.getFilePathHistoric() == null || Global.getFilePathReservations() == null || Global.getFilePathRooms() == null || Global.getFilePathStatus() == null;
    }
    
    private void cargaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaEstadoActionPerformed
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv", "csv");
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int result = file.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            Global.setFilePathStatus(file.getSelectedFile());
            nombreArcEstado.setText(Global.getFilePathStatus().getName());
            JOptionPane.showMessageDialog(null, "Su archivo de estado a sido cargado con exito");
        }
    }//GEN-LAST:event_cargaEstadoActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        if (FileIsEmpty()){
            //SE MUESTRA UN MENSAJE DE ERROR EN CASO DE QUE NO SE HAYA SELECCIONADO NINGUN ARCHIVO
            JOptionPane.showMessageDialog(null, "Debe seleccionar los archivos primero");
        }else{
            try {
            //Cargamos los hash tables.
            Global.cvsReaderHash();
            
            // Cargamos los datos y creamos los arboles.
            Global.cvsReaderReservations();
            Global.cvsReaderRoomsHistory();

            //Convertimos a False a las habitaciones que no se encuentra disponibles.
            Global.getClients().notAvailableRooms();
            // Creamos la ventana principal.
            Menu menu= new Menu();
            menu.setVisible(true);
            this.dispose();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "¡Ups! Algo salio mal...verifica");
            }
            
        }
    }//GEN-LAST:event_menuActionPerformed

    private void cargarReservacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarReservacActionPerformed
        //Para cargar el archivo
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv", "csv");
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int result = file.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            Global.setFilePathReservations(file.getSelectedFile());
            nombreArcRes.setText(Global.getFilePathReservations().getName());
            JOptionPane.showMessageDialog(null, "Su archivo de reservaciones a sido cargado con exito");
        }                
    }//GEN-LAST:event_cargarReservacActionPerformed

    private void cargarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarHabitacionesActionPerformed
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv", "csv");
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int result = file.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            Global.setFilePathRooms(file.getSelectedFile());
            nombreArcHabit.setText(Global.getFilePathRooms().getName());
            JOptionPane.showMessageDialog(null, "Su archivo de habitaciones a sido cargado con exito");
        }
    }//GEN-LAST:event_cargarHabitacionesActionPerformed

    private void cargaHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaHistoricoActionPerformed
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv", "csv");
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int result = file.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            Global.setFilePathHistoric(file.getSelectedFile());
            nombreArcHistor.setText(Global.getFilePathHistoric().getName());
            JOptionPane.showMessageDialog(null, "Su archivo de historico a sido cargado con exito");
        }
    }//GEN-LAST:event_cargaHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargaEstado;
    private javax.swing.JButton cargaHistorico;
    private javax.swing.JButton cargarHabitaciones;
    private javax.swing.JButton cargarReservac;
    private javax.swing.JPanel cargarReservaciones;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton menu;
    private javax.swing.JLabel nombreArcEstado;
    private javax.swing.JLabel nombreArcHabit;
    private javax.swing.JLabel nombreArcHistor;
    private javax.swing.JLabel nombreArcRes;
    // End of variables declaration//GEN-END:variables
}
