/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author pjroj
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setTitle("Menú");
        setSize(560, 510);
        setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salida = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cargaArcVentan1 = new javax.swing.JButton();
        buscarCliente1 = new javax.swing.JButton();
        busquedaReservac1 = new javax.swing.JButton();
        historialReserv = new javax.swing.JButton();
        checkIn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salida.setBackground(new java.awt.Color(51, 102, 255));
        salida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        salida.setText("Salir");
        salida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        jPanel2.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 150, 30));

        checkOut.setBackground(new java.awt.Color(51, 102, 255));
        checkOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        checkOut.setText("Check-Out");
        checkOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        jPanel2.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 230, 40));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reception");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cargaArcVentan1.setBackground(new java.awt.Color(51, 102, 255));
        cargaArcVentan1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cargaArcVentan1.setText("Cargar archivos nuevamente");
        cargaArcVentan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargaArcVentan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaArcVentan1ActionPerformed(evt);
            }
        });
        jPanel2.add(cargaArcVentan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, 40));

        buscarCliente1.setBackground(new java.awt.Color(51, 102, 255));
        buscarCliente1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buscarCliente1.setText("Buscar Cliente");
        buscarCliente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCliente1ActionPerformed(evt);
            }
        });
        jPanel2.add(buscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 40));

        busquedaReservac1.setBackground(new java.awt.Color(51, 102, 255));
        busquedaReservac1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        busquedaReservac1.setText("Busqueda de Reservación");
        busquedaReservac1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        busquedaReservac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaReservac1ActionPerformed(evt);
            }
        });
        jPanel2.add(busquedaReservac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 40));

        historialReserv.setBackground(new java.awt.Color(51, 102, 255));
        historialReserv.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        historialReserv.setText("Historial de Habitación");
        historialReserv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        historialReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialReservActionPerformed(evt);
            }
        });
        jPanel2.add(historialReserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 40));

        checkIn1.setBackground(new java.awt.Color(51, 102, 255));
        checkIn1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        checkIn1.setText("Check-In");
        checkIn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn1ActionPerformed(evt);
            }
        });
        jPanel2.add(checkIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 310, 510));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hotel5.png"))); // NOI18N
        imagen.setPreferredSize(new java.awt.Dimension(106, 102));
        jPanel3.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 390, 500));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 180, 510));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hotel5.png"))); // NOI18N
        imagen1.setPreferredSize(new java.awt.Dimension(106, 102));
        jPanel4.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 210, 500));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        CheckOut checkOut = new CheckOut();
        checkOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkOutActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        //
    }//GEN-LAST:event_salidaActionPerformed

    private void cargaArcVentan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaArcVentan1ActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cargaArcVentan1ActionPerformed

    private void buscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCliente1ActionPerformed
        BuscarCliente buscarC = new BuscarCliente();
        buscarC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarCliente1ActionPerformed

    private void busquedaReservac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaReservac1ActionPerformed
        BuscarReservacion buscarR =  new BuscarReservacion();
        buscarR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_busquedaReservac1ActionPerformed

    private void historialReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialReservActionPerformed
        HistorialHabitacion histHab =  new HistorialHabitacion();
        histHab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historialReservActionPerformed

    private void checkIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn1ActionPerformed
        CheckIn checkIn = new CheckIn();
        checkIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkIn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCliente1;
    private javax.swing.JButton busquedaReservac1;
    private javax.swing.JButton cargaArcVentan1;
    private javax.swing.JButton checkIn1;
    private javax.swing.JButton checkOut;
    private javax.swing.JButton historialReserv;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton salida;
    // End of variables declaration//GEN-END:variables
}
