/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author pjroj
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menú");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        salida = new javax.swing.JButton();
        search_room_history_btn = new javax.swing.JButton();
        search_client_btn = new javax.swing.JButton();
        search_reservation_btn = new javax.swing.JButton();
        check_in_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        check_out_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 800, 510));
        setMinimumSize(new java.awt.Dimension(800, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Kubo Sans", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 248, 231));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-HOTEL-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 170, -1));

        salida.setBackground(new java.awt.Color(255, 0, 51));
        salida.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        salida.setForeground(new java.awt.Color(255, 255, 255));
        salida.setText("Salir");
        salida.setAlignmentY(0.0F);
        salida.setBorder(null);
        salida.setOpaque(true);
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        getContentPane().add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 70, 30));

        search_room_history_btn.setBackground(new java.awt.Color(255, 248, 231));
        search_room_history_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        search_room_history_btn.setForeground(new java.awt.Color(75, 25, 0));
        search_room_history_btn.setText("Historial de Habitación");
        search_room_history_btn.setAlignmentY(0.0F);
        search_room_history_btn.setBorder(null);
        search_room_history_btn.setOpaque(true);
        search_room_history_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_room_history_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_room_history_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 210, 40));

        search_client_btn.setBackground(new java.awt.Color(255, 248, 231));
        search_client_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        search_client_btn.setForeground(new java.awt.Color(75, 25, 0));
        search_client_btn.setText("Buscar Cliente");
        search_client_btn.setAlignmentY(0.0F);
        search_client_btn.setBorder(null);
        search_client_btn.setBorderPainted(false);
        search_client_btn.setOpaque(true);
        search_client_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_client_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_client_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 210, 40));

        search_reservation_btn.setBackground(new java.awt.Color(255, 248, 231));
        search_reservation_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        search_reservation_btn.setForeground(new java.awt.Color(75, 25, 0));
        search_reservation_btn.setText("Buscar Reservación");
        search_reservation_btn.setAlignmentY(0.0F);
        search_reservation_btn.setBorder(null);
        search_reservation_btn.setOpaque(true);
        search_reservation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_reservation_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_reservation_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 210, 40));

        check_in_btn.setBackground(new java.awt.Color(255, 248, 231));
        check_in_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        check_in_btn.setForeground(new java.awt.Color(75, 25, 0));
        check_in_btn.setText("Check-In");
        check_in_btn.setAlignmentY(0.0F);
        check_in_btn.setBorder(null);
        check_in_btn.setOpaque(true);
        check_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_btnActionPerformed(evt);
            }
        });
        getContentPane().add(check_in_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 210, 40));

        jLabel2.setBackground(new java.awt.Color(255, 248, 231));
        jLabel2.setFont(new java.awt.Font("Kubo Sans", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 248, 231));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TERRAVILA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 370, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, -1, 510));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 510));

        check_out_btn.setBackground(new java.awt.Color(255, 248, 231));
        check_out_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        check_out_btn.setForeground(new java.awt.Color(75, 25, 0));
        check_out_btn.setText("Check-Out");
        check_out_btn.setAlignmentY(0.0F);
        check_out_btn.setBorder(null);
        check_out_btn.setOpaque(true);
        check_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_out_btnActionPerformed(evt);
            }
        });
        getContentPane().add(check_out_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu-Window.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel3.setBackground(new java.awt.Color(255, 248, 231));
        jLabel3.setFont(new java.awt.Font("Baskerville", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 248, 231));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TERRAVILA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 290, -1));

        jLabel4.setBackground(new java.awt.Color(255, 248, 231));
        jLabel4.setFont(new java.awt.Font("Baskerville", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 248, 231));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TERRAVILA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 290, -1));

        jLabel5.setBackground(new java.awt.Color(255, 248, 231));
        jLabel5.setFont(new java.awt.Font("Baskerville", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 248, 231));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TERRAVILA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_client_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_client_btnActionPerformed
        Search_Client window_2 = new Search_Client();
        window_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_search_client_btnActionPerformed

    private void check_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_out_btnActionPerformed
        Check_Out window_6 = new Check_Out();
        window_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_check_out_btnActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void search_reservation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_reservation_btnActionPerformed
        Search_Reservation window_3 = new Search_Reservation();
        window_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_search_reservation_btnActionPerformed

    private void search_room_history_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_room_history_btnActionPerformed
        Historic_Room window_4 = new Historic_Room();
        window_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_search_room_history_btnActionPerformed

    private void check_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_btnActionPerformed
        Check_In window_5 = new Check_In();
        window_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_check_in_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_in_btn;
    private javax.swing.JButton check_out_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton salida;
    private javax.swing.JButton search_client_btn;
    private javax.swing.JButton search_reservation_btn;
    private javax.swing.JButton search_room_history_btn;
    // End of variables declaration//GEN-END:variables
}
