package Interfaces;

import Main.Global;
import Classes.Class_Reservation;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pjroj
 */
public class Search_Client extends javax.swing.JFrame {
    DefaultTableModel m1 = new DefaultTableModel();
    
    /**
     * Método constructor de la clase.
     */
    public Search_Client() {
        initComponents();
        setTitle("Buscar Cliente");
        setResizable(false);
        this.setLocationRelativeTo(null);
        
        // LOS ATRIBUTOS DE LAS COLUMNAS.
        String ids[] = {"Habitación","Nombre","Apellido","Email","Género","Teléfono","Llegada del Cliente"};
        
        // SETEAMOS LOS ATRIBUTOS DE LA TABLA.
        m1.setColumnIdentifiers(ids);
        jTable1.setModel(m1);
        
        // DEFINIMOS EL TAMAÑO DE LAS CELDAS.
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        search_client_btn = new javax.swing.JButton();
        JLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        JLabel3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back_to_menu_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(0, 51, 102));
        menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menu.setText("Ir al menú");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        jLabel4.setFont(new java.awt.Font("Kubo Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 25, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUSCAR CLIENTE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 390, -1));

        search_client_btn.setBackground(new java.awt.Color(75, 25, 0));
        search_client_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        search_client_btn.setForeground(new java.awt.Color(255, 248, 231));
        search_client_btn.setText("Aceptar");
        search_client_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_client_btn.setOpaque(true);
        search_client_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_client_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_client_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 100, 30));

        JLabel4.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(75, 25, 0));
        JLabel4.setText("Primer nombre:");
        getContentPane().add(JLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 20));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 210, -1));

        JLabel3.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(75, 25, 0));
        JLabel3.setText("Segundo nombre:");
        getContentPane().add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 180, 20));
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 210, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 990, 150));

        back_to_menu_btn.setBackground(new java.awt.Color(75, 25, 0));
        back_to_menu_btn.setFont(new java.awt.Font("Kubo Sans", 1, 14)); // NOI18N
        back_to_menu_btn.setForeground(new java.awt.Color(255, 248, 231));
        back_to_menu_btn.setText("Volver al menú");
        back_to_menu_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_to_menu_btn.setOpaque(true);
        back_to_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_menu_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_to_menu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 130, 30));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Window_Search_Client.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_client_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_client_btnActionPerformed

        try {
            // Se reinicia la tabla de busqueda si ya se buscó anteriormente alguna reservación.
            if (m1.getRowCount() != 0) {
                while (m1.getRowCount() != 0){
                    m1.removeRow(0);
                }
            }

            String nam = name.getText().substring(0, 1).toUpperCase() + name.getText().substring(1).toLowerCase();
            String lastnam = lastname.getText().substring(0, 1).toUpperCase() + lastname.getText().substring(1).toLowerCase();
            //se busca al cliente
            Class_Reservation search_result = Global.getClients().searchClient(nam, lastnam);
            
            name.setText("");
            lastname.setText("");

            if (!"".equals(search_result)) {
                m1.addRow(new Object[]{search_result.getClient().getRoomNumber(),search_result.getClient().getName(),search_result.getClient().getLastname(),search_result.getClient().getEmail(),search_result.getClient().getGender(),search_result.getClient().getPhone(),search_result.getArrival()});
            } else {
                JOptionPane.showMessageDialog(null, "¡Cliente no encontrado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error! Búsqueda fallida!");
        }
    }//GEN-LAST:event_search_client_btnActionPerformed

    private void back_to_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_menu_btnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_to_menu_btnActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton back_to_menu_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton menu;
    private javax.swing.JTextField name;
    private javax.swing.JButton search_client_btn;
    // End of variables declaration//GEN-END:variables
}
